# Generated by Django 5.2.3 on 2025-06-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='tagsapp.blog')),
            ],
        ),
    ]
